name: obcsapi-go # 项目名称
version: v4.2.0 # 项目版本
description: by kkbt # 描述
host: 0.0.0.0 
port: 8900
token_path: ./token/ # token 文件位置。可用于云函数挂载硬盘位置
token1_live_time: 72h # 可设置有效期 至少 3 天 也可以设置 9999h


# 前端登录账户密码 有效时间 720h
user: kkbt 
password: password
general_allowed: false

# 前端后地址 邮件中登录链接会用到
front_url: https://kkbt.gitee.io/obweb/#/Memos
backend_url: api.ftls.xyz
backend_url_full: http://localhost:8900

# S3 -> 1 ; CouchDb -> 2 ; Local -> 3 ; WebDav -> 4
data_source: 3

# CouchDb 配置
couchdb_url: http://admin:password@localhost:5984/
couchdb_db_name: note

# S3 配置
access_key: xxxxxxxxxxxxxx
secret_key: xxxxxxxxxxxxxx
end_point: https://cos.ap-beijing.myqcloud.com
region: ap-beijing
bucket: obsidion-xxxxxxxxxxxxxx

# WeDav 配置
web_dav_url: https://dav.jianguoyun.com/dav/
web_dav_dir: note/
web_dav_username: xxxxxxx@qq.com
web_dav_password: xxxxxxxxxxxxxxxx


# wechat 测试号/公众号
wechat_token: xxxxxxxxxxxxxx # 微信公众平台的Token
wechat_appid: xxxxxxxxxxxxxx # 微信公众平台的AppID
wechat_secret: xxxxxxxxxxxxxx # 微信公众平台的AppSecret
wechat_openid: xxxxxxxxxxxxxx # OpenID 关注测试号后获取的
wechat_template_id: xxxxxxxxxxxxxx # 微信模板消息 ID 需要有 {{content.DATA}}

# 任务提醒
cron: "1/60 * * * * ?" # 每分钟检查一次 
