name: obcsapi-go
version: v1.0.0
description: by kkbt
host: 0.0.0.0
port: 9000
token_path: ./token/
token1_live_time: 24h

# 前端地址 纯静态文件 可以使用
front_url: https://ftls.xyz/test2.html
backend_url: http://127.0.0.1:8080

# smtp 邮箱服务
smtp_mail:
  smtp_host: smtpdm.aliyun.com
  port: 80
  username: no-reply@mail.ftls.xyz
  password: a4dsa4A3sadCFk2sjaD
  # 以下一个是发送者 一个是接受者
  mail_sender_address: no-reply@mail.ftls.xyz
  mail_sender_name: "ObCSAPI"
  mail_send_to: snowandocean@foxmail.com