name: obcsapi-go
version: v1.0.1
description: by kkbt
host: 0.0.0.0
port: 9000
token_path: ./token/
token1_live_time: 24h

# 前端后地址 邮件中登录链接会用到
front_url: http://127.0.0.1:8080/index.html
backend_url: api.ftls.xyz/ob

# S3 配置
access_key: xxxxxxxxxxxxxx
secret_key: xxxxxxxxxxxxxx
end_point: https://cos.ap-beijing.myqcloud.com
region: ap-beijing
bucket: obsidion-xxxxxxxxxxxxxx

# wechat 测试号/公众号
wechat_token: xxxxxxxxxxxxxx # 微信公众平台的Token
wechat_appid: xxxxxxxxxxxxxx # 微信公众平台的AppID
wechat_secret: xxxxxxxxxxxxxx # 微信公众平台的AppSecret
wechat_openid: xxxxxxxxxxxxxx # OpenID

# smtp 邮箱服务
smtp_mail:
  smtp_host: smtpdm.aliyun.com
  port: 80
  username: no-reply@mail.ftls.xyz
  password: xxxxxxxxxxxxxx
  # 以下一个是发送者 一个是接受者
  mail_sender_address: no-reply@mail.ftls.xyz
  mail_sender_name: "ObCSAPI"
  mail_send_to: snowandocean@foxmail.com