name: obcsapi-go
version: v1.0.0
description: by kkbt
host: 0.0.0.0
port: 9000
token_path: ./

# smtp 邮箱服务
smtp_mail:
  smtp_host: smtpdm.aliyun.com
  port: 80
  username: no-reply@some.domain
  password: no-reply-password
