name: obcsapi-go
version: v4.1.0
description: by kkbt
host: 0.0.0.0
port: 8900
token_path: ./token/
token1_live_time: 72h

# 前端后地址 邮件中登录链接会用到
front_url: https://kkbt.gitee.io/obweb/#/Memos
backend_url: api.ftls.xyz
wechat_return_str: "📩 已保存，<a href='https://note.ftls.xyz/#/ZK/202209050658'>点击查看今日笔记</a>"

# Obsidian 文件夹设置

ob_daily_dir: 日志/
ob_daily_attachment_dir: 日志/附件/
ob_daily_other_dir: 支持类文件/
# 图床文件 有四部分构成 url 文件夹及前缀，原名字，随机字符
# 图床文件夹及文件前缀 eg 2006-01-02 15:04:05 如 按月存放是 01/ ; 按 年存放 2006/ ; 文件前缀 200601 ; 文件夹和文件前缀 200601/200601_
images_hosted_url: http://localhost:8900/images/
images_hosted_fmt: 200601/kkbt_
images_hosted_use_raw_name: true # 图床文件是否使用原名字 true or false
images_hosted_random_name_length: 5 # 图床文件随机字符命名 随机字符长度
# 百度 OCR https://ai.baidu.com/ai-doc/OCR/zk3h7xz52 该项置空或删除此项则不进行 OCR 注意该项有效期 30 天
# https://ai.baidu.com/ai-doc/REFERENCE/Ck3dwjhhu
# bd_ocr_access_token: xxxxx.xxxxx.xxxxx.xxxxx.xxxxx-xxxxx

# S3 -> 1 ; CouchDb -> 2 ; Local -> 3
data_source: 3

# CouchDb 配置
couchdb_url: http://admin:password@localhost:5984/
couchdb_db_name: note

# S3 配置
access_key: xxxxxxxxxxxxxx
secret_key: xxxxxxxxxxxxxx
end_point: https://cos.ap-beijing.myqcloud.com
region: ap-beijing
bucket: obsidion-xxxxxxxxxxxxxx

# LocalStorage (RemotelySave WebDav) http://localhost:8900/webdav 用户自定义账户密码
webdav_server: true
webdav_username: kkbt
webdav_password: kkbt123
webdav_dir: testdb/

# wechat 测试号/公众号
wechat_token: xxxxxxxxxxxxxx # 微信公众平台的Token
wechat_appid: xxxxxxxxxxxxxx # 微信公众平台的AppID
wechat_secret: xxxxxxxxxxxxxx # 微信公众平台的AppSecret
wechat_openid: xxxxxxxxxxxxxx # OpenID
wechat_template_id: xxxxxxxxxxxxxx # 微信模板消息 ID 需要有 {{content.DATA}}

# 任务提醒
email_reminder_time: 0700 # 指每天 07:00 

# smtp 邮箱服务
smtp_mail:
  smtp_host: smtpdm.aliyun.com
  port: 80
  username: no-reply@mail.ftls.xyz
  password: xxxxxxxxxxxxxx
  # 以下一个是发送者 一个是接受者
  mail_sender_address: no-reply@mail.ftls.xyz
  mail_sender_name: "ObCSAPI"
  mail_send_to: yourmail@foxmail.com